services:

  php:
   
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: adv-library-php
    working_dir: /app
    command: ./vendor/bin/phpunit
    volumes:
      - .:/app
 
    ports:
      - "9000:9000"
   
